version: "3"
services:
  node:
    image: "node:15.10.0"
    user: "node"
#    network_mode: host
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
      - "8080:8080"
    command: tail -F anything
    container_name: webservice
